import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createCounterfactualReplay,evaluateBatch,normalizeObservation,verifyClose,DATASET_TYPE,STATUS} from '../src/observation.mjs';
const raw=JSON.parse(fs.readFileSync(new URL('../data/betpawa-real-world-observation-batch-v0.1.json',import.meta.url)));
const evaluation=evaluateBatch(raw);
test('five independent BetPawa legs settle exactly 2-3 with hit rate .40',()=>{assert.equal(evaluation.n,5);assert.equal(evaluation.wins,2);assert.equal(evaluation.losses,3);assert.equal(evaluation.hit_rate,.4);assert.deepEqual(evaluation.observations.map(x=>x.outcome),['LOSS','LOSS','WIN','WIN','LOSS']);assert.equal(new Set(evaluation.observations.map(x=>x.observation_id)).size,5);assert.ok(evaluation.observations.every(x=>x.provider==='BetPawa'));});
test('P002 is isolated and frozen contract remains byte-specific',()=>{const p002=fs.readFileSync(new URL('../../../contracts/p002-frozen-rules.json',import.meta.url),'utf8');assert.equal(JSON.parse(p002).lineage,'P002');assert.equal(evaluation.dataset_type,DATASET_TYPE);assert.equal(evaluation.status,STATUS);assert.ok(evaluation.observations.every(x=>x.dataset_type!== 'P002'&&!('pattern_id' in x)));});
test('unknown provenance remains NULL and archive makes no prematch claim',()=>{for(const x of evaluation.observations){assert.equal(x.event_id,null);assert.equal(x.competition,null);assert.equal(x.season,null);assert.equal(x.kickoff_at,null);assert.equal(x.entry_observed_at,null);assert.equal(x.closing_odds,null);assert.equal(x.clv,null);assert.equal(x.ingestion_timing,'POST_EVENT_ARCHIVAL');}});
test('bookmaker benchmark is named and model scores are absent',()=>{assert.equal(evaluation.brier,null);assert.equal(evaluation.log_loss,null);assert.equal(evaluation.clv_n,0);assert.match(evaluation.metric_note,/no verified pre-match system probabilities/i);assert.ok(evaluation.bookmaker_implied_probability_benchmark_mean>0);});
test('cross-provider and post-kickoff close cannot produce CLV',()=>{const base={...evaluation.observations[0],state:'SETTLED',event_id:'event-1',kickoff_at:'2026-01-01T12:00:00Z'};assert.throws(()=>verifyClose(base,{provider:'1xBet',odds:2,observed_at:'2026-01-01T11:00:00Z'}),/CROSS_PROVIDER/);assert.throws(()=>verifyClose(base,{provider:'BetPawa',odds:2,observed_at:'2026-01-01T12:00:00Z'}),/POST_KICKOFF/);});
test('settlement evidence is frozen and cannot be rewritten',()=>{const x=evaluation.observations[0];assert.ok(Object.isFrozen(x));assert.throws(()=>{x.selection='AWAY'},TypeError);assert.throws(()=>{x.entry_odds=9},TypeError);});
test('settled user observation cannot be relabelled system frozen signal',()=>{assert.throws(()=>normalizeObservation({...raw,observation_source:'SYSTEM_FROZEN_1X2_SIGNAL'},raw.observations[0]),/CANNOT_BECOME_FROZEN_SIGNAL/);});
test('pre-match claims require timestamps strictly before kickoff',()=>{assert.throws(()=>normalizeObservation({...raw,ingestion_timing:'PRE_KICKOFF_VERIFIED'},{...raw.observations[0],kickoff_at:'2026-01-01T12:00:00Z',entry_observed_at:'2026-01-01T12:00:00Z'}),/PREMATCH_ENTRY_NOT_VERIFIED/);});
test('counterfactual replay rejects cross-event, after-kickoff and leaked inputs',()=>{const o={...evaluation.observations[0],event_id:'event-a',kickoff_at:'2026-01-01T12:00:00Z'};const good={replay_id:'r1',event_id:'event-a',cutoff_at:'2026-01-01T11:00:00Z',decision:'ABSTAIN',probabilities:{home:.4,draw:.3,away:.3},inputs:{odds:[2,3,4]},created_at:'2026-01-02T00:00:00Z'};assert.equal(createCounterfactualReplay(o,good).decision,'ABSTAIN');assert.throws(()=>createCounterfactualReplay(o,{...good,event_id:'event-b'}),/CROSS_EVENT/);assert.throws(()=>createCounterfactualReplay(o,{...good,cutoff_at:'2026-01-01T12:00:01Z'}),/AFTER_KICKOFF/);assert.throws(()=>createCounterfactualReplay(o,{...good,inputs:{settlement:{home:1,away:0}}}),/LEAKAGE/);assert.throws(()=>createCounterfactualReplay(o,{...good,inputs:{features:{settlement:{home:1}}}}),/LEAKAGE/);const a=createCounterfactualReplay(o,good);const b=createCounterfactualReplay(o,{...good,decision:'HOME'});assert.notEqual(a.input_fingerprint,b.input_fingerprint);});
test('verified close recomputes a payload fingerprint bound to its evidence',()=>{const base={...evaluation.observations[0],state:'SETTLED',event_id:'event-1',kickoff_at:'2026-01-01T12:00:00Z'};const a=verifyClose(base,{provider:'BetPawa',odds:2,observed_at:'2026-01-01T11:00:00Z'});const b=verifyClose(base,{provider:'BetPawa',odds:1.9,observed_at:'2026-01-01T11:00:00Z'});assert.notEqual(a.payload_fingerprint,base.payload_fingerprint);assert.notEqual(a.payload_fingerprint,b.payload_fingerprint);});

test('replay snapshots nested caller data before hashing and persistence',()=>{const o={...evaluation.observations[0],event_id:'event-a',kickoff_at:'2026-01-01T12:00:00Z'};const probabilities={home:.4,draw:.3,away:.3},flags=['LOW_SAMPLE'],inputs={features:{odds:[2,3,4]}};const replay=createCounterfactualReplay(o,{replay_id:'snapshot',event_id:'event-a',cutoff_at:'2026-01-01T11:00:00Z',decision:'ABSTAIN',probabilities,flags,inputs,created_at:'2026-01-02T00:00:00Z'});probabilities.home=.9;flags.push('MUTATED');inputs.features.odds[0]=99;assert.deepEqual(replay.probabilities,{away:.3,draw:.3,home:.4});assert.deepEqual(replay.flags,['LOW_SAMPLE']);assert.deepEqual(replay.inputs.features.odds,[2,3,4]);assert.ok(Object.isFrozen(replay.inputs.features.odds));});
test('compound hindsight field names are rejected recursively',()=>{const o={...evaluation.observations[0],event_id:'event-a',kickoff_at:'2026-01-01T12:00:00Z'};const base={replay_id:'compound',event_id:'event-a',cutoff_at:'2026-01-01T11:00:00Z',decision:'ABSTAIN',probabilities:{home:.4,draw:.3,away:.3},created_at:'2026-01-02T00:00:00Z'};assert.throws(()=>createCounterfactualReplay(o,{...base,inputs:{features:{postKickoffOdds:1.8}}}),/LEAKAGE/);assert.throws(()=>createCounterfactualReplay(o,{...base,inputs:{finalScoreHome:3}}),/LEAKAGE/);});
test('duplicate observation identities reject before evaluation or persistence',()=>{assert.throws(()=>evaluateBatch({...raw,observations:[raw.observations[0],raw.observations[0]]}),/DUPLICATE_OBSERVATION_ID/);});
