import test from 'node:test';import assert from 'node:assert/strict';
import {appendMarketObservation,buildFullMarketInference,buildIndependentTeamState,buildMarketConsistencyGraph,buildMatchupAudit,buildMatchWorlds,devigMarketObservations,recomputeJointSelection,settleSystemSignalAndUserExecution} from '../src/full-market-inference.mjs';
import {buildScoreDistribution} from '../src/bidirectional-match-reasoning.mjs';

const frozenAt='2026-08-31T10:00:00Z',kickoffAt='2026-08-31T12:00:00Z';
function state(teamId,{n=12,xi=.9,current={attack:.7,defence:.6,playerQuality:.7,teamQuality:.7,teamCohesion:.7,tacticalQuality:.7}}={}){
 return buildIndependentTeamState({teamId,asOf:frozenAt,currentSeasonSample:n,previousSeason:{attack:.6,defence:.6,playerQuality:.6,teamQuality:.6,teamCohesion:.6,tacticalQuality:.6},currentSeason:current,xiConfidence:xi,evidence:[{source:'gate1',observedAt:'2026-08-31T09:00:00Z',verified:true,type:'FORM'}]});
}
function obs({id,family,selection,line=null,odds,group,source='provider'}){
 return {observationId:id,marketGroupId:group,completeMarket:true,marketFamily:family,selection,line,odds,provider:'BetPawa',source,observedAt:'2026-08-31T09:30:00Z',marketSnapshotId:'snap-1'};
}
function base(overrides={}){
 const observations=[
  obs({id:'h',family:'1X2_FULL_TIME',selection:'HOME',odds:1.45,group:'1x2'}),
  obs({id:'d',family:'1X2_FULL_TIME',selection:'DRAW',odds:4.5,group:'1x2'}),
  obs({id:'a',family:'1X2_FULL_TIME',selection:'AWAY',odds:8,group:'1x2'}),
  obs({id:'o35',family:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'OVER',line:3.5,odds:2.4,group:'t35'}),
  obs({id:'u35',family:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'UNDER',line:3.5,odds:1.6,group:'t35'})
 ];
 return {eventId:'event-1',analysisTimestamp:'2026-08-31T09:55:00Z',kickoffAt,homeTeam:'Home',awayTeam:'Away',homeLambda:1.65,awayLambda:.75,
  teamAState:state('home'),teamBState:state('away'),marketObservations:observations,marketSelections:[
   {marketFamily:'1X2_FULL_TIME',selection:'HOME'},{marketFamily:'1X2_FULL_TIME',selection:'AWAY'},
   {marketFamily:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'UNDER',line:3.5},{marketFamily:'CORNERS',selection:'OVER',line:10.5}],
  modelVersion:'model-v1',featureVersion:'feature-v1',marketSnapshotId:'snap-1',frozenAt,modelConfidence:.9,...overrides};
}

test('lowest odds do not automatically become PRIMARY and strong favourite can reject',()=>{const out=buildFullMarketInference(base());assert.notEqual(out.primary_candidate?.marketFamily,'1X2_FULL_TIME');const home=out.candidate_outcomes.find(x=>x.marketFamily==='1X2_FULL_TIME'&&x.selection==='HOME');assert.match(home.classification,/ABSTAIN/);});
test('underdog can become candidate when distribution beats fair market',()=>{const b=base({homeLambda:1.05,awayLambda:1.25});b.marketObservations=b.marketObservations.map(x=>x.observationId==='a'?{...x,odds:6}:x);const out=buildFullMarketInference(b);const away=out.candidate_outcomes.find(x=>x.selection==='AWAY');assert.ok(away.edge>0);assert.equal(away.classification,'CANDIDATE');});
test('possession alone cannot imply control',()=>{const audit=buildMatchupAudit(state('a'),state('b'),{POSSESSION_QUALITY:{differential:.8,confidence:.9,source:'stats',observedAt:frozenAt}});assert.equal(audit.possession_quality_not_control,true);assert.equal(audit.concepts.TACTICAL_AMPLIFICATION.status,'UNKNOWN');});
test('early-season low N exposes weights, penalty and uncertainty',()=>{const x=state('early',{n:2});assert.equal(x.sample_size,2);assert.ok(x.prior_weight>x.current_season_weight);assert.ok(x.early_season_penalty>state('mature').early_season_penalty);assert.ok(x.state_uncertainty>0);});
test('O2.5 short plus expensive BTTS emits asymmetric scoring contradiction',()=>{const rows=devigMarketObservations([
 obs({id:'o25',family:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'OVER',line:2.5,odds:1.35,group:'t25'}),
 obs({id:'u25',family:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'UNDER',line:2.5,odds:3.8,group:'t25'}),
 obs({id:'by',family:'BTTS_FULL_TIME',selection:'YES',odds:2.4,group:'btts'}),
 obs({id:'bn',family:'BTTS_FULL_TIME',selection:'NO',odds:1.55,group:'btts'})],frozenAt,kickoffAt);const graph=buildMarketConsistencyGraph(rows);assert.equal(graph.edges[0].contradiction_type,'TOTAL_HIGH_BTTS_LOW');assert.ok(graph.edges[0].possible_explanations.includes('ASYMMETRIC_SCORING_EXPECTATION'));assert.equal(graph.trap_claim_made,false);});
test('related home win and team-total markets generate contradiction',()=>{const rows=devigMarketObservations([
 obs({id:'h',family:'1X2_FULL_TIME',selection:'HOME',odds:1.2,group:'x'}),obs({id:'d',family:'1X2_FULL_TIME',selection:'DRAW',odds:7,group:'x'}),obs({id:'a',family:'1X2_FULL_TIME',selection:'AWAY',odds:14,group:'x'}),
 obs({id:'ho',family:'HOME_TEAM_OVER_UNDER_FULL_TIME',selection:'OVER',line:1.5,odds:2.3,group:'ht'}),obs({id:'hu',family:'HOME_TEAM_OVER_UNDER_FULL_TIME',selection:'UNDER',line:1.5,odds:1.6,group:'ht'})],frozenAt,kickoffAt);assert.ok(buildMarketConsistencyGraph(rows).edges.some(x=>x.contradiction_type==='HOME_WIN_VS_HOME_SCORING'));});
test('strong Under plus weak Home does not imply strong joint selection',()=>{const dist=buildScoreDistribution({homeLambda:1.1,awayLambda:.9});const joint=recomputeJointSelection(dist,[{marketFamily:'1X2_FULL_TIME',selection:'HOME'},{marketFamily:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'UNDER',line:3.5}],{jointOdds:2});assert.equal(joint.status,'MODELLED');assert.ok(joint.joint_probability<joint.component_probabilities[1]);assert.notEqual(joint.joint_probability,joint.component_probabilities[0]*joint.component_probabilities[1]);});
test('user execution loss does not rewrite successful system signal',()=>{const signal=Object.freeze({immutable:true,signal_id:'s1',marketFamily:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'UNDER',line:3.5});const settled=settleSystemSignalAndUserExecution({systemSignal:signal,userExecution:{execution_id:'u1',components:[{marketFamily:'1X2_FULL_TIME',selection:'HOME'},{marketFamily:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'UNDER',line:3.5}]},homeScore:0,awayScore:1,settledAt:'2026-08-31T14:00:00Z'});assert.equal(settled.system_signal.result,'WIN');assert.equal(settled.user_execution.result,'LOSS');});
test('unsupported market returns UNSUPPORTED without probability',()=>{const row=buildFullMarketInference(base()).candidate_outcomes.find(x=>x.marketFamily==='CORNERS');assert.equal(row.classification,'UNSUPPORTED');assert.equal(row.model_probability,null);});
test('missing market provenance blocks candidate promotion',()=>{const b=base();b.marketObservations=b.marketObservations.map(x=>x.observationId==='u35'?{...x,source:null}:x);const out=buildFullMarketInference(b);const row=out.candidate_outcomes.find(x=>x.selection==='UNDER');assert.equal(row.classification,'ABSTAIN_MISSING_PROVENANCE');assert.ok(out.abstain_reasons.includes('MARKET_PROVENANCE_MISSING'));});
test('uncertain XI reduces confidence',()=>{const mature=buildFullMarketInference(base());const uncertain=buildFullMarketInference(base({teamAState:state('home',{xi:.4}),teamBState:state('away',{xi:.4})}));const key=x=>x.candidate_outcomes.find(r=>r.selection==='UNDER').confidence;assert.ok(key(uncertain)<key(mature));});
test('post-kickoff evidence cannot mutate frozen signal',()=>{const out=buildFullMarketInference(base());assert.ok(Object.isFrozen(out));assert.throws(()=>{out.home_probability=.99},TypeError);const b=base();b.marketObservations=[{...b.marketObservations[0],observedAt:'2026-08-31T10:01:00Z'}];assert.throws(()=>buildFullMarketInference(b),/AFTER_FREEZE/);});
test('market movement appends a new observation without mutating history',()=>{const history=appendMarketObservation([],{observationId:'m1',odds:2,observedAt:'2026-08-31T09:00:00Z'});const next=appendMarketObservation(history,{observationId:'m2',odds:1.8,observedAt:'2026-08-31T09:30:00Z'});assert.equal(history.length,1);assert.equal(next.length,2);assert.ok(Object.isFrozen(history[0]));});
test('candidate ranking is deterministic for identical frozen inputs',()=>{const a=buildFullMarketInference(base()),b=buildFullMarketInference(base());assert.equal(a.fingerprint,b.fingerprint);assert.deepEqual(a.candidate_outcomes.map(x=>[x.marketFamily,x.selection,x.tier]),b.candidate_outcomes.map(x=>[x.marketFamily,x.selection,x.tier]));});
test('match worlds form a coherent exhaustive partition',()=>{const worlds=buildMatchWorlds(buildScoreDistribution({homeLambda:1.4,awayLambda:1.1}));assert.ok(Math.abs(worlds.reduce((s,x)=>s+x.probability,0)-1)<1e-9);assert.ok(worlds.every(x=>x.score_family.length>0));});

test('de-vig isolates provider and snapshot observations sharing a market group id',()=>{const rows=devigMarketObservations([
 {...obs({id:'p1h',family:'1X2_FULL_TIME',selection:'HOME',odds:2,group:'shared'}),provider:'P1',marketSnapshotId:'s1'},
 {...obs({id:'p1a',family:'1X2_FULL_TIME',selection:'AWAY',odds:2,group:'shared'}),provider:'P1',marketSnapshotId:'s1'},
 {...obs({id:'p2h',family:'1X2_FULL_TIME',selection:'HOME',odds:4,group:'shared'}),provider:'P2',marketSnapshotId:'s2'},
 {...obs({id:'p2a',family:'1X2_FULL_TIME',selection:'AWAY',odds:4/3,group:'shared'}),provider:'P2',marketSnapshotId:'s2'}
],frozenAt,kickoffAt);const sum=provider=>rows.filter(x=>x.provider===provider).reduce((s,x)=>s+x.market_fair_probability,0);assert.ok(Math.abs(sum('P1')-1)<1e-12);assert.ok(Math.abs(sum('P2')-1)<1e-12);assert.equal(rows.find(x=>x.observationId==='p1h').market_fair_probability,.5);assert.equal(rows.find(x=>x.observationId==='p2h').market_fair_probability,.25);});
test('team-state completeness counts missing required quality dimensions',()=>{const x=buildIndependentTeamState({teamId:'sparse',asOf:frozenAt,currentSeasonSample:4,previousSeason:{attack:.6},currentSeason:{attack:.7},xiConfidence:.8,evidence:[{source:'gate1',observedAt:'2026-08-31T09:00:00Z',verified:true,type:'FORM'}]});assert.equal(x.data_completeness,.2);assert.equal(x.quality_separation.PLAYER_QUALITY,null);assert.equal(x.quality_separation.TACTICAL_QUALITY,null);});
test('score-derived multigoals and any exact correct score remain modelled',()=>{const b=base({marketSelections:[{marketFamily:'MULTIGOALS_FULL_TIME',selection:'2-4'},{marketFamily:'CORRECT_SCORE_FULL_TIME',selection:'4-2'}]});b.marketObservations=[
 obs({id:'mg',family:'MULTIGOALS_FULL_TIME',selection:'2-4',odds:1.9,group:'mg'}),
 obs({id:'cs',family:'CORRECT_SCORE_FULL_TIME',selection:'4-2',odds:30,group:'cs'})
];const out=buildFullMarketInference(b);for(const row of out.candidate_outcomes){assert.notEqual(row.classification,'UNSUPPORTED');assert.ok(Number.isFinite(row.model_probability));assert.ok(row.model_probability>0);}});
test('integer totals preserve PUSH mass in joints and settlement',()=>{const dist=buildScoreDistribution({homeLambda:1.2,awayLambda:.8});const joint=recomputeJointSelection(dist,[{marketFamily:'1X2_FULL_TIME',selection:'HOME'},{marketFamily:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'UNDER',line:2}],{jointOdds:2.5});assert.equal(joint.status,'MODELLED');assert.ok(joint.joint_push_probability>0);const signal=Object.freeze({immutable:true,signal_id:'push-1',marketFamily:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'UNDER',line:2});const settled=settleSystemSignalAndUserExecution({systemSignal:signal,homeScore:1,awayScore:1,settledAt:'2026-08-31T14:00:00Z'});assert.equal(settled.system_signal.components[0].status,'PUSH');assert.equal(settled.system_signal.result,'PUSH');});

test('candidate ranking is bound to the requested frozen market snapshot regardless of history order',()=>{const historical=[
 {...obs({id:'old-o',family:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'OVER',line:3.5,odds:1.5,group:'old-t35'}),marketSnapshotId:'old'},
 {...obs({id:'old-u',family:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'UNDER',line:3.5,odds:3,group:'old-t35'}),marketSnapshotId:'old'},
 {...obs({id:'new-o',family:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'OVER',line:3.5,odds:6,group:'new-t35'}),marketSnapshotId:'new'},
 {...obs({id:'new-u',family:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'UNDER',line:3.5,odds:1.2,group:'new-t35'}),marketSnapshotId:'new'}
];const input={marketSnapshotId:'new',marketObservations:historical,marketSelections:[{marketFamily:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'UNDER',line:3.5}]};const a=buildFullMarketInference(base(input)),b=buildFullMarketInference(base({...input,marketObservations:[...historical].reverse()}));assert.equal(a.candidate_outcomes[0].fair_market_probability,b.candidate_outcomes[0].fair_market_probability);assert.equal(a.candidate_outcomes[0].classification,b.candidate_outcomes[0].classification);assert.equal(a.candidate_outcomes[0].supporting_evidence[0],'new-u');});
test('team states newer than the frozen signal are rejected',()=>{const future=buildIndependentTeamState({teamId:'future',asOf:'2026-08-31T10:01:00Z',currentSeasonSample:3,previousSeason:{attack:.6},currentSeason:{attack:.7},xiConfidence:.8,evidence:[{source:'gate1',observedAt:'2026-08-31T10:01:00Z',verified:true,type:'FORM'}]});assert.throws(()=>buildFullMarketInference(base({teamAState:future})),/TEAM_STATE_AFTER_FREEZE/);});
test('integer-line model probabilities are conditional on non-push outcomes',()=>{const dist=buildScoreDistribution({homeLambda:1.2,awayLambda:.8});const joint=recomputeJointSelection(dist,[{marketFamily:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'OVER',line:2},{marketFamily:'BTTS_FULL_TIME',selection:'YES'}]);const win=dist.rows.filter(x=>x.totalGoals>2).reduce((s,x)=>s+x.probability,0),loss=dist.rows.filter(x=>x.totalGoals<2).reduce((s,x)=>s+x.probability,0);assert.ok(Math.abs(joint.component_probabilities[0]-win/(win+loss))<1e-12);assert.ok(Math.abs(joint.component_probabilities[0]-win)>1e-3);});

test('later append-only market history cannot block replay of the requested frozen snapshot',()=>{const b=base();b.marketObservations.push({...obs({id:'later-u',family:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'UNDER',line:3.5,odds:1.4,group:'later'}),marketSnapshotId:'snap-later',observedAt:'2026-08-31T10:01:00Z'});const out=buildFullMarketInference(b);assert.equal(out.market_snapshot_id,'snap-1');assert.ok(out.market_observations.every(x=>x.marketSnapshotId==='snap-1'));assert.ok(!out.market_observations.some(x=>x.observationId==='later-u'));});
test('post-freeze matchup evidence is rejected from the immutable signal',()=>{assert.throws(()=>buildFullMarketInference(base({matchupConceptEvidence:{POSSESSION_QUALITY:{differential:.4,confidence:.8,source:'stats',observedAt:'2026-08-31T10:01:00Z'}}})),/MATCHUP_EVIDENCE_AFTER_FREEZE/);});
test('joint pricing probability and edge are conditioned on non-push outcomes',()=>{const dist=buildScoreDistribution({homeLambda:1.2,awayLambda:.8});const joint=recomputeJointSelection(dist,[{marketFamily:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'OVER',line:2},{marketFamily:'BTTS_FULL_TIME',selection:'YES'}],{jointMarketProbability:.25});assert.ok(joint.joint_push_probability>0);assert.ok(Math.abs(joint.joint_probability-joint.joint_unconditional_win_probability/(1-joint.joint_push_probability))<1e-12);assert.ok(Math.abs(joint.joint_edge-(joint.joint_probability-.25))<1e-12);});

test('joint dependency uses component marginals from the same joint settlement space',()=>{const dist=buildScoreDistribution({homeLambda:1.2,awayLambda:.8});const joint=recomputeJointSelection(dist,[{marketFamily:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'OVER',line:2},{marketFamily:'BTTS_FULL_TIME',selection:'YES'}]);const p11=dist.rows.find(x=>x.homeGoals===1&&x.awayGoals===1).probability,active=1-p11,overWin=dist.rows.filter(x=>x.totalGoals>2).reduce((s,x)=>s+x.probability,0),bttsActiveWin=dist.rows.filter(x=>x.homeGoals>0&&x.awayGoals>0&&x.totalGoals!==2).reduce((s,x)=>s+x.probability,0),expectedProduct=(overWin/active)*(bttsActiveWin/active);assert.ok(Math.abs(joint.joint_conditioned_component_probabilities[0]-overWin/active)<1e-12);assert.ok(Math.abs(joint.dependency-(joint.joint_probability-expectedProduct))<1e-12);});
test('unknown market selections are UNSUPPORTED rather than coerced to a valid side',()=>{const b=base({marketSelections:[{marketFamily:'DRAW_NO_BET_FULL_TIME',selection:'DRAW'}],marketObservations:[obs({id:'bad-dnb',family:'DRAW_NO_BET_FULL_TIME',selection:'DRAW',odds:2,group:'bad'})]});const out=buildFullMarketInference(b);assert.equal(out.candidate_outcomes[0].classification,'UNSUPPORTED');assert.equal(out.candidate_outcomes[0].model_probability,null);const signal=Object.freeze({immutable:true,signal_id:'bad',marketFamily:'DRAW_NO_BET_FULL_TIME',selection:'DRAW'});const settled=settleSystemSignalAndUserExecution({systemSignal:signal,homeScore:1,awayScore:0,settledAt:'2026-08-31T14:00:00Z'});assert.equal(settled.system_signal.result,'UNSUPPORTED');});
test('settlement rejects negative fractional and non-numeric football scores',()=>{const signal=Object.freeze({immutable:true,signal_id:'score-check',marketFamily:'1X2_FULL_TIME',selection:'HOME'});for(const [homeScore,awayScore] of [[-1,0],[1.5,0],['1',0],[1,NaN]])assert.throws(()=>settleSystemSignalAndUserExecution({systemSignal:signal,homeScore,awayScore,settledAt:'2026-08-31T14:00:00Z'}),/FINAL_SCORE_INVALID/);});

test('unsupported negative and quarter goal lines are never modelled or settled',()=>{for(const line of [-1,2.25]){const b=base({marketSelections:[{marketFamily:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'OVER',line}],marketObservations:[obs({id:'bad-line-'+line,family:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'OVER',line,odds:2,group:'bad-line'})]});assert.equal(buildFullMarketInference(b).candidate_outcomes[0].classification,'UNSUPPORTED');const signal=Object.freeze({immutable:true,signal_id:'bad-line',marketFamily:'TOTAL_GOALS_OVER_UNDER_FULL_TIME',selection:'OVER',line});assert.equal(settleSystemSignalAndUserExecution({systemSignal:signal,homeScore:2,awayScore:1,settledAt:'2026-08-31T14:00:00Z'}).system_signal.result,'UNSUPPORTED');}});
test('multigoals requires anchored ordered non-negative integer bounds',()=>{for(const selection of ['garbage2x4suffix','4-2']){const b=base({marketSelections:[{marketFamily:'MULTIGOALS_FULL_TIME',selection}],marketObservations:[obs({id:'bad-mg-'+selection,family:'MULTIGOALS_FULL_TIME',selection,odds:2,group:'bad-mg'})]});assert.equal(buildFullMarketInference(b).candidate_outcomes[0].classification,'UNSUPPORTED');}});
test('score-derived selections outside the finite distribution support are UNSUPPORTED',()=>{const b=base({marketSelections:[{marketFamily:'CORRECT_SCORE_FULL_TIME',selection:'13-0'},{marketFamily:'TOTAL_GOALS_EXACT_FULL_TIME',selection:'25'}],marketObservations:[obs({id:'cs13',family:'CORRECT_SCORE_FULL_TIME',selection:'13-0',odds:100,group:'cs13'}),obs({id:'tg25',family:'TOTAL_GOALS_EXACT_FULL_TIME',selection:'25',odds:100,group:'tg25'})]});const out=buildFullMarketInference(b);assert.ok(out.candidate_outcomes.every(x=>x.classification==='UNSUPPORTED'&&x.model_probability===null));});

test('post-freeze market timestamps are rejected even when other provenance is incomplete',()=>{const b=base({marketObservations:[{...obs({id:'late-incomplete',family:'1X2_FULL_TIME',selection:'HOME',odds:2,group:'late'}),source:null,observedAt:'2026-08-31T10:01:00Z'}]});assert.throws(()=>buildFullMarketInference(b),/MARKET_OBSERVATION_AFTER_FREEZE/);});
test('joint recomputation rejects any component outside distribution support',()=>{const dist=buildScoreDistribution({homeLambda:1.2,awayLambda:.8});const joint=recomputeJointSelection(dist,[{marketFamily:'CORRECT_SCORE_FULL_TIME',selection:'13-0'},{marketFamily:'BTTS_FULL_TIME',selection:'YES'}]);assert.equal(joint.status,'UNSUPPORTED');assert.equal(joint.joint_probability,null);assert.equal(joint.component_probabilities[0],null);});
test('explicit multigoals bounds form distinct candidate identities',()=>{const selections=[{marketFamily:'MULTIGOALS_FULL_TIME',minGoals:0,maxGoals:1},{marketFamily:'MULTIGOALS_FULL_TIME',minGoals:2,maxGoals:4}],observations=[{...obs({id:'mg01',family:'MULTIGOALS_FULL_TIME',selection:undefined,odds:2,group:'mg01'}),minGoals:0,maxGoals:1},{...obs({id:'mg24',family:'MULTIGOALS_FULL_TIME',selection:undefined,odds:2,group:'mg24'}),minGoals:2,maxGoals:4}];const out=buildFullMarketInference(base({marketSelections:selections,marketObservations:observations}));assert.equal(out.candidate_outcomes.length,2);assert.ok(out.candidate_outcomes.every(x=>Number.isFinite(x.model_probability)));assert.deepEqual(new Set(out.candidate_outcomes.map(x=>x.supporting_evidence[0])),new Set(['mg01','mg24']));});
